### ISSUE TITLE
Newly added breaches have broken images for logos until manually loaded

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1013]
## Steps to reproduce

1. Go to https://fx-breach-alerts.herokuapp.com/breach-details/OrdineAvvocatiDiRoma
2. Witness.

### Actual results

Logo is a broken image.

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/58395871-1cea0e80-7fff-11e9-80c2-07b09093c74d.png)

### Expected results

Not sure if we can use a placeholder image or something less broken looking until a breach logo is loaded. I can't remember what the status was of the script that automatically downloaded+optimized breach images, or if that was lost in a shuffle of AWS+GCP migration work.

**Comment by lesleyjanenorton** [comment]
Closing since this is now fixed. The script to automatically download and optimize breach images was lost in the migration shuffle and I'm not sure how we'd approach it now, given that the image requirements (must be of approximately equal height and width, must not be white) have changed and we can't always pull them from HIBP.
