### ISSUE TITLE
"What do do after a data breach" has a trailing colon

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1024]
via jdavidson in Slack:

> https://monitor.firefox.com/breach-details/Houzz — see the blue link under the Change your password tip that says “What to do after a data breach:” — it looks like that’s an error?

![Slack_-_Mozilla](https://user-images.githubusercontent.com/557895/58499970-114d3380-8136-11e9-9a14-b810b31d0bfb.png)

Ryan Gaddis also pointed to this design spec:

![Slack_-_Mozilla](https://user-images.githubusercontent.com/557895/58500020-33df4c80-8136-11e9-9517-563314cda2e2.png)

---

via _Originally posted by @pdehaan in https://github.com/mozilla/blurts-server/issues/1011#issuecomment-496014499_

The label for the "Change your password" section seems wrong (only one with a semicolon).

![](https://user-images.githubusercontent.com/557895/58384720-eaf29100-7f99-11e9-9e27-06e98db68d03.png)

---

**UPDATE 1:** Rogue trailing semicolon, it's also visible on the homepage:

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/58494781-bd891d00-812a-11e9-87e6-5e0726bf89f4.png)

---

**UPDATE 2:** Also on the security tips page heading:

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/58504985-b967fa00-8140-11e9-997b-2e5a3a78b05f.png)

**Comment by pdehaan** [comment]
The semi-interesting thing is that "What do do after a data breach:" is used as both a heading and link text. So I _think_ we need two l10n strings, one with a trailing colon and one without.

**Comment by betsymi** [comment]
Addressed this in #1034, but putting it here too for visibility since two things need to change:

+ Remove colon from "What to do after a data breach" string entirely so it no longer appears here or on Security Tips content block that surfaces elsewhere
+ Adjust headline to **What to do after a website breach:** with a colon. On the handful of data aggregators, this should read **What to do after a data aggregator breach:** with a colon. 

![Colon Confusion](https://user-images.githubusercontent.com/43555492/58568789-79654d80-81fa-11e9-8ec1-28e1e3df2946.png)
