### ISSUE TITLE
Unable to login to Firefox Monitor using Firefox or Brave. Issue not present using Edge.

### ISSUE THREAD

**Issue by tobiaalberti** [mozilla/blurts-server#1084]
Hello,
I was instructed to report this bug here by @groovecoder on Twitter:
https://twitter.com/groovecoder/status/1137412678186614786

**The issue:**
If I visit https://monitor.firefox.com/ using the Firefox browser or the Brave browser, and try to log in using my Firefox account, after having provided my email address, password, MFA code, and having clicked "Verify", I'm met with the following error message:

![Attachment](https://user-images.githubusercontent.com/30185056/59151084-a18c5200-8a2d-11e9-8abc-97486e72b5ab.png)

**The temporary workaround:**
Funnily enough if I try to log in to Firefox Monitor with the same Firefox account using Microsoft Edge, no bug is present and I'm able to log in successfully.

**More info:**
Listed here are version numbers of the browsers and OSes used as well as a few other information that might be relevant.

*Firefox browser (Version 67.0.1)*
Tested the bug both in regular and Private mode by disabling all add-ons and by setting Content Blocking to Standard.

*Brave browser (Version 0.65.118 Chromium: 75.0.3770.80)*
Tested the bug by disabling all extensions, and by disabling some built-in privacy and security settings.

*Edge browser (Version 44.17763.1.0)*
Test done with all extensions disabled.

*Device (laptop)*
Windows 10 (Version 1809 OS Build 17763.529)

Before being confronted with this bug (a few days ago) I was able to successfully add all my email addresses to Firefox Monitor.

I hope you'll be able to reproduce, identify, and fix this soon.
Kind Regards.

**Comment by pdehaan** [comment]
Thanks for the bug report, I'll take a look this morning and see if I can reproduce the issue.
Possibly the same issue as #1067.

**Comment by tobiaalberti** [comment]
> 
> 
> Thanks for the bug report, I'll take a look this morning and see if I can reproduce the issue.
> Possibly the same issue as #1067.

Any update on a possible fix? The issue appears to be indeed similar to #1067. The differences are:
1. I only tested this by manually typing monitor.firefox.com directly in my address bar, never by clicking links on related Mozilla blog posts.
2. Reloading the page after the sign in process is unsuccessful doesn't fix it.

**Comment by pdehaan** [comment]
I was able to test this on macOS w/ Firefox Release channel and Firefox Nightly (using a regular and private window or w/ Content Blocking: Standard), but wasn't able to reproduce the issue locally.

I can take a look again this weekend on my Windows 10 laptop (sorry, I'm travelling this week and don't have access to my other devices). But the fact that it seems to work in other browsers makes me suspect that it may be possibly related to some Firefox configs or other plugins that may be blocking cookies from Firefox Accounts which tracks that you're logged in. I'll also try creating a new Firefox Account and do some more testing around MFA since I see you mentioned that above, and I don't recall if my testing Firefox Account had two step authentication enabled.

**Comment by angejens** [comment]
I have the same problem and think it might be due to adding too many email addresses to be monitored. In my original account, I have 10 email addresses to be monitored. I created a second account and had no problems until I added the 9th email address. I tried this in Firefox and Google Chrome and got the error, but did not have problems with Edge

**Comment by LucasDiTomase** [comment]
Hi. I am having the same issue. I have Firefox monitor set up with 11 email addresses and the only browser I can sign in to is Microsoft Edge. Firefox Stable, Firefox Nightly, Safari and Chrome (both Stable and Canary) throw the same error as pointed out in the screenshot. Please somebody take a look at it and fix it if possible. Thanks!

**Comment by LucasDiTomase** [comment]
I would also like to add that this is platform independent. The issue has happened to me in Windows 10 (all browsers except Microsoft Edge) , MacOS Catalina and iOS 13.

**Comment by bitnapper** [comment]
Having the same issue with current MacOS and iOS with the lates version of the firefox browser.

**Comment by LucasDiTomase** [comment]
This happening here too

#1146

**Comment by rfk** [comment]
>  I have Firefox monitor set up with 11 email addresses and the only browser
> I can sign in to is Microsoft Edge.

Aha! I was able to reproduce this by adding a bunch of email addresses to Monitor. Step to reproduce:

* Sign in to Monitor with your Firefox Account.
* Go to https://monitor.firefox.com/user/preferences
* Add a lot of additional email addresses to monitor (I added 11 of them)
* Sign out of Monitor
* Attempt to sign back in to Monitor

Expected results:

* Successfully sign back in to Monitor

Actual results:

* Error: "you must be signed in to your Firefox Account"


Because I kept a separate login session to Monitor open while testing this, I was able to delete some of the additional email addresses, which in turn stopped the error from occurring.

---

Observing the network traffic during my failed login attempt, I see that the request that completes the OAuth dance is trying to set a **gigantic** cookie:

```
> GET https://monitor.firefox.com/oauth/confirmed?code=[...]&state=[...]&action=signin
.
< 302 Found
< Location: /user/dashboard
< Set-Cookie: session=[...around 4kb of base64-encoded data...]
```

Monitor uses the [session-cookie](https://www.npmjs.com/package/client-sessions) package to maintain user sessions in encrypted client-side cookies. So what I think is happening is:

* At the end of the signin process, Monitor looks up all the profile information for the user and tries to store it all in an encrypted cookie
* With sufficiently many additional emails on the account, the size of this cookie exceeds the maximum allowed by the browser
* The browser refuses to store the gigantic cookie, so the login doesn't "stick"
* The following request to `/user/dashboard` sends the previous, pre-login version of the session cookie and monitor correctly refuses to serve the user dashboard when no user is signed in.

The fact that it works on Edge but not in Firefox, may be due to differences in the maximum allowed size of cookies between different browsers.

The solution here is probably to store less profile information in the session cookie (maybe just the primary email address and userid) and look up other info from the DB on demand.

**Comment by rfk** [comment]
> The fact that it works on Edge but not in Firefox, may be due to differences in the
> maximum allowed size of cookies between different browsers.

According to [this website I found for testing cookie limits](http://browsercookielimits.squawky.net/), Firefox has a max size of 4097 while Edge allows 5117. So yeah.

**Comment by ashishthukral** [comment]
@rfk that makes sense, i added about 8-9 email addresses and was in process to add couple more for my family.

**Comment by lissyx** [comment]
> Observing the network traffic during my failed login attempt, I see that the request that completes the OAuth dance is trying to set a **gigantic** cookie:

Cookie being set is 7k (7194 chars according to `wc`).

**Comment by LucasDiTomase** [comment]
When you guys fix this issue please let people add multiple accounts I haven’t finished adding addresses yet 😂 Thanks

**Comment by groovecoder** [comment]
@rfk awesome thanks for finding this underlying cause of the bug!! I'll get started on a fix ASAP when I get back on Monday.

**Comment by tobiaalberti** [comment]
Hello,
I'm still experiencing the very same bug over here.
I'm confused as to why you decided to mark this issue as "Closed"?

**Comment by LucasDiTomase** [comment]
Same here 👆

**Comment by pdehaan** [comment]
Re: closed bug

The core bug has been fixed in GitHub, but we’ll still need to deploy it to the production server in order to see the correct behavior.

**Comment by tobiaalberti** [comment]
> 
> 
> Re: closed bug
> 
> The core bug has been fixed in GitHub, but we’ll still need to deploy it to the production server in order to see the correct behavior.

Thank you for the clarification 🙂
Do you know when we can expect the fix to be deployed to the production server?

**Comment by groovecoder** [comment]
The fix for this issue is now deployed. Thank you everyone for your patience!

**Comment by LucasDiTomase** [comment]
I can confirm on my end, fix is working as intended ( with 14 email addresses ) on Chrome latest stable version. Thanks so much!

**Comment by GecoMynx** [comment]
I can confirm it, too. It's working like a charm now :)

**Comment by ashishthukral** [comment]
yep working. thanks guys.

**Comment by tobiaalberti** [comment]
> 
> 
> The fix for this issue is now deployed. Thank you everyone for your patience!

Thanks. I'm now able to login correctly.

**Comment by Flux3PO** [comment]
HI everyone, @groovecoder was pointing me here.
I'm also interested in having this fixed. I was able to add 30+ Email addresses and I was hoping to get all my alias addresses to be added to Monitor, which are about 350+.
Might sound crazy to some of you, but I'm using one alias per service, to easily switch compromised addresses, when required. This also enables me to see where the spam is coming from...

Hope this gets addressed at some point !
