### ISSUE TITLE
[Mobile] Don't scroll the main page when trying to scroll the Bento menu while in landscape mode

### ISSUE THREAD

**Issue by csuciu** [mozilla/blurts-server#1232]
1. Visit https://monitor-v2.herokuapp.com/.
2. Turn the device in landscape mode.
3. Open Bento menu.
4. Try to scroll in Bento menu.

Expected behavior:
The main page doesn't scroll when trying to scroll in Bento menu.

Actual behaviour:
The main page is scrolled.

Device: iPhone XS (iOS 12.4), Samsung Galaxy S10+ (Android 9).
Firefox versions: Latest Firefox iOS/Android
 
For more details please check https://user-images.githubusercontent.com/42831109/65893155-2bcb3e00-e3b0-11e9-8180-a2cc1e4ad230.gif

**Comment by lesleyjanenorton** [comment]
I think this is a question for product and UX - I'm not sure if we want to restrict scrolling in this scenario or not.

**Comment by changecourse** [comment]
I think it's fine to maintain scrolling within landscape mode as it's currently functioning... it can be a little finicky, between two vertically-scrollable containers, but after playing with it for a bit, I don't think that the alternative proposed as expected above would be any better, as someone would intentionally have to close or dismiss the bento in order to navigate the rest of the page, and it may not be obvious to do so (since the bento only takes up a small portion of the screen on landscape)

**Comment by lesleyjanenorton** [comment]
Closing - the ability to scroll the page while the bento is open is intentional. Thanks!
