### ISSUE TITLE
Add catch-all addresses

### ISSUE THREAD

**Issue by HWiese1980** [mozilla/blurts-server#1327]
I'm using a catch-all address on my own domain. I'd love to see a way to add that address to Firefox Monitor and monitor basically *@mydomain.com or similar.

**Comment by jhotmann** [comment]
Similarly, I am using AnonAddy as a proxy for my real email address and use a different email for each website for privacy and security reasons. Something like `websitename@mysubdomain.anonaddy.com` so that `*@mysubdomain.anonaddy.com` is automatically forwarded to my main inbox. It would be time consuming to add each new alias to monitor, so catch-all support would be a lifesaver. To verify, just generate a random string and send an email to that address at the domain/subdomain.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
