### ISSUE TITLE
Recruit research participants, who are signed into FxA, via a survey prompt

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#1486]
Opening a ticket to implement the structure to:
* deliver a recruitment survey prompt
* that takes the user through a surveygismo survey
* starting with users who are signed into the site

Still developing requirements with @jenniferdavidson

**Comment by jenniferdavidson** [comment]
Here are my thoughts! 

Requirements regardless of the structure specifics (banner or link): 
* Have the ability to turn off (we want to be able to shut down the message when we get enough survey responses -- we don't want to oversample)
* Be able to know impressions, and how many people clicked the survey invitation. This will help us calculate a response rate to the survey, which is important for future surveys to know how many people we should release it to, how long it should run, when we can turn it off. 
* Be able to segment by locale (for example, only show on en*. I'll be running interviews in English this round, so it should only show on a page that's in the English.) 
* A flag to understand if someone is signed in or not (for example, we may want it to show on only signed in pages) 
* Show on the page that shows after someone is signed in. 
* Bonus: "Global": Will show on every page until dismissed. 
* Bonus: Only show on X% of pages (so we could perhaps, show to 10% of sessions, to avoid oversampling too quickly) 

Requirements for the structure itself (**if it's a banner**): 
* Be dismissable
* Have space for a message
* Have 1 button or link on it that can open a link to a survey 

Requirements if it's **a link** somewhere on the page: 
* Be obviously optional! 
* The link should open a survey 

**Requirements for the specific implementation for the upcoming research study (assuming it's a banner):** 
* en*, except in countries where we cannot distribute incentives 
* Review with @betsymi , but have language that says something like: "We want to hear from you! Get paid to participate in a research study about your experience with Firefox Monitor.” 
* Button/Link text: [I’m interested]
* Link that the button goes to: TBD (It will be a survey link, but I haven't created it yet)
* Show only for users who are signed in to Firefox Monitor

And tagging @changecourse , because your design input on where/how the survey should be presented would be great. 

Here's an example of a survey from AMO: https://github.com/mozilla/addons-frontend/pull/5620. Not that this is a different type of survey, but the design could potentially be borrowed.

**Comment by jenniferdavidson** [comment]
* Disappear after they select "take the survey" or X it out 
* Implement analytics on this so we can tell # of views, & # of clicks on the button & # of clicks on dismiss (this will help future messages and surveys know if we can show it to less people and still get the response rate we need)
* Think of this as a component that we can reuse for future messages as needed
* Try at first with the message underneath the global nav, and see how that looks
* en* as the primary accepted language

**Comment by jenniferdavidson** [comment]
@lesleyjanenorton -- Here's the string we can start with: "Share your experience about Monitor with the Firefox team and participate in a paid research study." [I'm Interested] -- after we take the dev version to crit, we can adjust if needed!
