### ISSUE TITLE
"Verify your email" links params start with "&" instead of "?"

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1552]
Google Analytics isn't properly parsing the utm parameter values from links in the "Verify your email" email.

![image](https://user-images.githubusercontent.com/71928/74752563-7e5ca800-5234-11ea-8014-e4f69f86dcd1.png)

Looks like the link is:

`/user/verify&utm...`

when it should be:

`/user/verify?utm...`

?

**Comment by pdehaan** [comment]
I feel like it would be coming from somewhere around here:

https://github.com/mozilla/blurts-server/blob/85561f3c99a4b6c5799a763519588541764ee93d/email-utils.js#L108-L113

Curiously, the code seems to append a `token` query param which appends the `verification_token` to the query string. I didn't see that in the screenshot above, but maybe we're removing the token before passing it along to GA.

Unclear if reversing these two lines would help at all:

```js
url.searchParams.append("token", encodeURIComponent(subscriber.verification_token));
url = this.appendUtmParams(url, "verified-subscribers", "account-verification-email");
```

**Comment by maxxcrawford** [comment]
@pdehaan is right. I'm not able to reproduce this locally, because the token is getting correctly injected. Are there any instances where a verification token would **not** be injected in the email? 

_(Stripped token contents for this screenshot)_ 
![image](https://user-images.githubusercontent.com/2692333/76468632-6d79ff00-63ba-11ea-80a3-6a64c3ac9c05.png)
