### ISSUE TITLE
[Experiment] Scan Results page FxA Sign-up Buttons are not pre-populating the FxA form with the scanned email address

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#1627]
## Steps to Reproduce: 

1. Go to site on the control branch: https://monitor-v2.herokuapp.com/?experimentBranch=va
1. Enter email address and click "Check for Breaches" button
1. On /scans page, click either "Alert me about new breaches" buttons.

Expected: 
- User is presented FxA page with submitted email address already filled out. 

Actual: 
- User is prompted to enter email address again 

Notes:
- Issue looks like it is reproducible in **ALL THREE** branches.

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible using Firefox Release 74.0 (Build ID 20200309095159) and Microsoft Edge (v. 44.18362.449.0) on Windows 10 (x64), Firefox 24 on iOS 12.4.5 (iPhone 5s), as well as Firefox Preview 4.1.0 (Build #20771637) on Android 9 (Samsung Galaxy 8).
The email is pre-populated for all three branches in the case of both the "Alert me about new breaches" link and button. This applies to emails not associated with accounts as well as emails associated with accounts.
