### ISSUE TITLE
Add Phone to the database

### ISSUE THREAD

**Issue by tiziodcaio** [mozilla/blurts-server#2110]
I don't know if possible, but it would be cool monitoring my phone numbers too! Any comment appreciated 😊

**Comment by maverick74** [comment]
I would vote for this as well!

HIBP has this ability related to the latest FB breach and i believe it's a very important one!

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

**Comment by maverick74** [comment]
Well @EMMLynch , i would still like the possibility of searching if a phone number has been in any leak.

haveibeenpwned, removed the option (due to ?privacy concerns? ...I think...) but i still think it would be great to have the feature because a personal cell phone is just as important as a personal e-mail.

**Comment by EMMLynch** [comment]
Thanks @maverick74. I'll share this idea with the team.
