### ISSUE TITLE
Unlimited email addresses

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#2144]
The premium Monitor experience should include unlimited email addresses. Individual user stories (file sub-issues as needed):

* As a free user on the Monitor dashboard, I should see an "Upgrade" link to purchase a premium subscription, so I can add unlimited email addresses to monitor. UI points:
   * Bottom of email address list
   * "Manage email" screen
   * "5 addresses being monitored"
* As a premium user of the Monitor dashboard, I should be able to add as many email addresses as I want.
* As a premium user of the Monitor dashboard, I should be able to filter my email addresses to quickly find one.

**Comment by lsm5** [comment]
@groovecoder any updates on this issue? This would be really nice to have.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

**Comment by iTrooz** [comment]
![image](https://github.com/mozilla/blurts-server/assets/42669835/e99839f5-83b2-4a56-b038-0d08e65e26ea)
As a free user, I don't see an "upgrade" button when trying to add an email address. Instead, the "Send verification link" button will keep spinning (this doesn't happen when I have less than 5 emails registered)

Idk if that warrant reopening, since the text says "Up to 5 email addresses"
