### ISSUE TITLE
Blue links in emails should be consistently styled

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#2239]
'Unsubscribe' and 'Frequently Asked Questions' should match other blue links.
<img width="678" alt="Screen Shot 2021-07-26 at 9 05 41 PM" src="https://user-images.githubusercontent.com/22355127/127083637-af7ba8c9-2890-41ca-a417-f99fb60e8a00.png">

**Comment by Amod02-prog** [comment]
Hi , I would like to work on this issue.

**Comment by Amod02-prog** [comment]
Can you direct me to the location of the file issue.

**Comment by jwhitlock** [comment]
The text is translated, and identified by `email-footer-blurb`

The code that generates the HTML fragment is: 
https://github.com/mozilla/blurts-server/blob/a25eaecee9b9d132cd027f3d9cdb0d07e366dd7e/template-helpers/emails.js#L217-L237

I think this issue is the browser is styling visited links differently than unvisited links. I'm not sure if we want to override that.

**Comment by Amod02-prog** [comment]
@jwhitlock I don't think you are wrong here . I looked through the code and as you thought the links that can be visited are styled differently than rest . But in that piece of code , there are no indications to "Have I Been Pwned" yet still its been highlighted . I think that it could be a simple css color coding error where he first two and the last two have been given two different color codes which can be corrected easily except I am unable to find the .html file for that page or the .css file

**Comment by Amod02-prog** [comment]
@lesleyjanenorton Can you comment the link where we can see this result

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
