### ISSUE TITLE
Refresh the breach data periodically

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#245]
Per https://github.com/mozilla/blurts-server/pull/244#issuecomment-409706336 ...

Now that it's in process memory, we will either need to:

    Restart the server
    Use a thread (!) to refresh it
    Something else?

**Comment by pdehaan** [comment]
What about some "hidden" Express route which grabs the latest breach data and updates app.locals.breaches object using the same `await HIBP.loadBreachesIntoApp(app);` type code?

Of course, the risk there is that people may try calling that endpoint manually and cause mischief (unless we somehow debounce it so it is a noop if its called more than 1x every 12-24h). Something like `/admin/refreshbreaches`. Plus, since it would be just a vanilla route, it should be easy enough to set up some cron job to curl that GET/POST endpoint.

**Comment by groovecoder** [comment]
Since the breaches are loaded into process memory, we would need something to hit the `/hibp/refresh` route on each of the internal web nodes inside the ELB to make sure we refresh the breaches in all the app processes.

**Comment by nhnt11** [comment]
@pdehaan, that's genius, thanks! This would even solve the problem of keeping instances in sync, because we can ensure that the endpoint is called on instances. We could also probably easily restrict this endpoint to localhost to ensure that only the cron job or whatever can trigger it.

**Comment by pdehaan** [comment]
Or we could just try and cache using some clever Express middleware:

- https://medium.com/the-node-js-collection/simple-server-side-cache-for-express-js-with-node-js-45ff296ca0f0
- https://www.npmjs.com/package/apicache

I was trying to think of a way to perform the HIBP refresh in one of the dockerflow routes (like `/__heartbeat__` or `/__lbheartbeat__`) since OPs is already pinging those regularly, and if it's cached, we'd never do a sync more often than 12-24h anyways. But that may have some silly side effects like caching the "OK" response for a big period of time.

Not sure if HIBP has some way to determine when the HIBP database was last updated. Like if we could do a quick HEAD fetch and check for a `Last-Modified` header or something so we can signal if we need to do a sync or not. I'd hate to pull all the JSON and redownload all the logos every 24h if there weren't any changes. Oh, plus I guess that if there is a new breach, we'd also need to grab the logo and possibly run it through the SVGO or imagemin optimizers. Eeehhh... Probably way overkill to host all the logos in some shared CDN so we don't need to do the image processing on each WWW instance separately.

And we'd also need to make sure we do the same syncing w/ the add-on since IIRC we're baking the breaches.json and logos into the add-on as well.

**Comment by groovecoder** [comment]
Hmm ... the middle-ware approach is interesting. I don't think we could use one of those off-the-registry libraries, because they are designed to cache an entire route response.

But we could add a middle-ware that re-loads the breach data from HIBP. Something like every N seconds or every N requests. It would mean that single HTTP request on the node would have a couple extra seconds delay in delivering its response. But the `/scan` requests are already pinging HIBP for a few seconds.

So, if we wrap `/scan` requests in middle-ware that periodically reloads the breaches, we can get fresh breach data into the app process every N minutes/requests at the cost of adding 1-2s response time to a single HTTP request.

**Comment by pdehaan** [comment]
Actually, I touched on a CDN briefly in #164; "Better sharing of logos between add-on and server".

The more I think of it, the more interesting it sounds. Just a small+cheap CDN server which hosts the logos with ridiculously long expires headers, and possibly even hosts our own version of "breaches.json", which the web hosts can scrape during startup and then periodically update themselves.
But this way all the images and breach data may be stored in a single source of truth without needing the scraping logic on each WWW host and potentially downloading and doing image manipulation on the same images on X hosts.

The challenge of it would be seeing if we could maybe have the Firefox Monitor add-on code use the same CDN to avoid any data duplication. Plus it'd have to load the breach alert logos from the CDN instead of embedding them in the add-on (so we don't need to redeploy the add-on each time a new breach is added). I can't remember if @nhnt11 had any specific concerns around loading external assets/images in the add-on from an external source.

It'd be interesting to see if Troy has any advice on this since I assume he's thought about it.

**Comment by pdehaan** [comment]
> So, if we wrap `/scan` requests in middle-ware that periodically reloads the breaches, we can get fresh breach data into the app process every N minutes/requests at the cost of adding 1-2s response time to a single HTTP request.

I think I'd need somebody to prove to me that it is only a 1-2s penalty for a single user. If you're just talking breaches.json, sure, maybe a random user pay a small price. But if we're talking about having to keep logos in sync and possibly doing resizing and optimizing, I'm skeptical that we can do that within a tight 1-2s window.

**Comment by groovecoder** [comment]
Oh, yeah I was only thinking about the `breaches.json`

**Comment by nhnt11** [comment]
I was going through the UX spec draft with epang the other day, and it seems like we may not want breached-site-logos in the Firefox-UI after all - which reduces the appeal of a CDN setup.

**Comment by nhnt11** [comment]
FWIW I don't think we should update breaches using middleware that hooks into the /scan endpoint. Seems unreliable.

I honestly don't see anything wrong with just updating everything every 5 minutes - can we quantify the cost of this update operation so that we can decide how much engineering effort we need for this?

IMO, it's pretty important to be able to display info about new breaches quickly after a breach gets into the media - we want to be ready for people coming in to check it out.

What about hooking into the breach-notification callback that HIBP calls when there's a new breach?

**Comment by nhnt11** [comment]
Quick clarification: I said hooking into /scan feels unreliable because we also need to be able to support new breaches in the index endpoint when a breach is specified as a GET parameter.

Also, I realized that HIBP only triggers our callback if we have a hash-prefix subscribed, so that's a no-go.

**Comment by nhnt11** [comment]
I like the idea of fetching only headers, btw - I took a quick look at them and there doesn't seem to be a header that gives us information about when the data was updated, but maybe we can request this from Troy?

If this ends up working out, we could trigger an update when any of our endpoints is hit, and some arbitrary timeout has been exceeded since the last update. And the update operation would be pretty cheap unless there's actually new data, so we could be fairly aggressive with the timeout without much worry.

**Comment by groovecoder** [comment]
Because we hold the breach data in process memory, and node.js doesn't support threads, to update the data every 5 minutes, we have to either:

1. Introduce some kind of process restart/rotation; refreshes will be system-triggered (e.g., on a cron job)
2. Introduce some kind of master/worker process architecture; refreshes will be code-triggered
3. Add some code to the existing request/response code that refreshes the breach data during normal use of the app

I prefer option 3 at least for `breaches.json` data because of the simple architecture. I will have to think about if/whether/how to do the logos too.
