### ISSUE TITLE
add UUIDv4 validation to /user/verify route

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#255]
For belt+suspenders validation, we can validate that the verification token passed to /user/verify is UUIDv4 before checking the database.

**Comment by pdehaan** [comment]
Per https://fx-breach-alerts.herokuapp.com/user/verify?token=576a72dc-4727-4f97-8df1-11fef

Passing an invalid UUID v4 token seems to trigger an "Application error" on the [/user/verify?token=](https://fx-breach-alerts.herokuapp.com/user/verify?token=576a72dc-4727-4f97-8df1-11fef) route (at least on Heroku).

![invalid-token](https://user-images.githubusercontent.com/557895/43984518-e69872ea-9cb5-11e8-84fa-9a9aa23c9dca.png)

**Comment by pdehaan** [comment]
Other imaginary examples... I can do a POST to /user/add without a `req.body.email`, and then I just get weird, unhelpful error messages in the front end. It's a fairly bogus situation (since I can only POST using curl or httpie), but still...

```bash
$ curl -XPOST https://fx-breach-alerts.herokuapp.com/user/add

    ...
    <h2>Error</h2>
    <p> Cannot read property &#x27;normalize&#x27; of undefined </p>
```

Not 100% certain what/where that error is coming from yet. I can't find any references to `"normalize"` in our repo, outside of package names in package-lock.json.

**Comment by pdehaan** [comment]
https://fx-breach-alerts.herokuapp.com/user/verify

> #### Error
> Undefined binding(s) detected when compiling SELECT query: select * from "subscribers" where "verification_token" = ?

**Comment by groovecoder** [comment]
Good catch. Adding this to launch milestone.

**Comment by pdehaan** [comment]
I didn't go through all the GET/POST endpoints, but it may be worth it to make sure we aren't leaking any server info and have reasonable user-facing error messages.

After a bit of digging, I _think_ this is a maybe/hopefully accurate route map:

| METHOD | ROUTE | QUERY/BODY
|:-------|:------|:-----------
| GET  | "/" | `req.query.breach`❓ 
| GET  | "/\_\_version\_\_" | n/a
| GET  | "/\_\_heartbeat\_\_" | n/a
| GET  | "/\_\_lbheartbeat\_\_" | n/a
| POST | "/hibp/notify" | `req.body.breachName` `req.body.hashPrefix`
| GET  | "/hibp/breaches" | `req.headers["if-modified-since"]`
| POST | "/scan/" | `req.body.emailHash` `req.body.featuredBreach`❓
| GET  | "/scan/" | n/a
| POST | "/ses/notification" | `JSON.parse(req.body)`
| POST | "/user/add" | `req.body.email` `req.body.additionalEmails`
| GET  | "/user/verify" | `req.query.token`
| GET  | "/user/unsubscribe" | `req.query.token` `req.query.hash`
| POST | "/user/unsubscribe" | `req.body.token` `req.body.emailHash`
| GET  | "/user/unsubscribe_survey" | `req.session.unsub`❓
| POST | "/user/unsubscribe_survey" | n/a

Where it looks like params marked w/ "❓" may be optional.

**Comment by groovecoder** [comment]
Removing this from Launch Day milestone since the stacktrace issues are fixed in #420.

**Comment by pdehaan** [comment]
```bash
echo "POST /hibp/notify"
curl -s -XPOST https://fx-breach-alerts.herokuapp.com/hibp/notify | grep -A1 "<h2>Error</h2>"

# echo "GET /hibp/breaches"
# curl -s https://fx-breach-alerts.herokuapp.com/hibp/breaches

echo "POST /scan"
curl -s -XPOST https://fx-breach-alerts.herokuapp.com/scan/ | grep -A1 "<h2>Error</h2>"

# echo "POST /ses/notification"
# curl -s -XPOST https://fx-breach-alerts.herokuapp.com/ses/notification

echo "POST /user/add"
curl -s -XPOST https://fx-breach-alerts.herokuapp.com/user/add | grep -A1 "<h2>Error</h2>"

echo "GET /user/verify"
curl -s https://fx-breach-alerts.herokuapp.com/user/verify | grep -A1 "<h2>Error</h2>"

echo "GET /user/subscribe"
curl -s https://fx-breach-alerts.herokuapp.com/user/unsubscribe | grep -A1 "<h2>Error</h2>"

echo "POST /user/unsubscribe"
curl -s -XPOST https://fx-breach-alerts.herokuapp.com/user/unsubscribe | grep -A1 "<h2>Error</h2>"

echo "GET /user/unsubscribe_survey"
curl -s https://fx-breach-alerts.herokuapp.com/user/unsubscribe_survey | grep -A1 "<h2>Error</h2>"

echo "POST /user/unsubscribe_survey"
curl -s -XPOST https://fx-breach-alerts.herokuapp.com/user/unsubscribe_survey
```

### Output:

```
POST /hibp/notify
    <h2>Error</h2>
    <p> Cannot read property &#x27;toLowerCase&#x27; of undefined </p>

POST /scan

POST /user/add
    <h2>Error</h2>
    <p> Invalid Email </p>

GET /user/verify
    <h2>Error</h2>
    <p> Verification token is required. </p>

GET /user/subscribe
    <h2>Error</h2>
    <p> Undefined binding(s) detected when compiling SELECT query: select * from &quot;subscribers&quot; where &quot;verification_token&quot; &#x3D; ? </p>

POST /user/unsubscribe
    <h2>Error</h2>
    <p> Undefined binding(s) detected when compiling FIRST query: select * from &quot;subscribers&quot; where &quot;verification_token&quot; &#x3D; ? and &quot;sha1&quot; &#x3D; ? limit ? </p>

GET /user/unsubscribe_survey
    <h2>Error</h2>
    <p> This email address is not subscribed to Firefox Monitor. </p>

POST /user/unsubscribe_survey
{"title":"Firefox Monitor: Unsubscribed"}%
```

**Comment by groovecoder** [comment]
Pulling back out of Launch Day milestone since the other stacktraces are gone (again).

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
