### ISSUE TITLE
Consider adding an "Opt out" link to HIBP

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#466]
For users who don't want their email address to be searchable, Troy offers an opt-out page here:

https://haveibeenpwned.com/OptOut

We could link to this from somewhere on Monitor too.

**Comment by groovecoder** [comment]
A thought ... Work with Troy to provide a "make-my-data-private" mechanism. So after a subscriber has verified their email address, include a link in their emails to automatically opt them out of public display.

**Comment by targaryen** [comment]
It would be nice if this mechanism could bypass the requirement to disable strict tracking protection in order to use Google ReCaptcha service when opting out of the HIBP form  (if this will still be required if HIBP work with you to provide a 'make-my-data-private' mechanism). 

It's not an insurmountable difficulty, but requires users to understand why it broke and disable the relevant security controls.  The non-obvious nature of this confuses typical users, though, evidenced by a google search:

https://www.google.com/search?q=recaptcha+google+tracking+protection

And the submission page on HIBP does not detect these failures and provide instruction to overcome:

![image](https://user-images.githubusercontent.com/74666/46090300-ac3bdb00-c16d-11e8-94e7-a214b0002915.png)

Perhaps a mitigating factor to this being serious concern is that users must opt into strict tracking protection (double-opt, really... once to turn on tracking protection, and again to turn on strict tracking protection within settings) to enable strict privacy.  The setting comes with warnings about potentially breaking things, so if a user is sophisticated enough to understand and accept that, it might be argued that it is their own responsibility to figure out why things break once in a while.

The only disappointment to this being that by enabling configuration to use the ReCaptcha requires reduction in privacy controls for users who are already sensitive to privacy.  There's FUD, much of it old and possibly of date, but not able to be casually dismissed due to lack of transparency about the uses Google makes of some of the data collected when performing ReCaptcha.  

I know, maybe this is nitpicking a bit too far, but Firefox brand has Privacy as a huge benefot with a lot of controls, options, and work put into ensuring a private and trustable browser.  So I'd hope other services respect and contribute to the effort where it's possible.  In this case it's a bit out of your hands if you simply re-point to HIBP OptOut page, and working with HIBP for special non-captcha'd API for an option directly within Firefox Monitor is extra work for both parties, and nobody's time comes lightly.  

I can accept a temporary reduction on those grounds, but my fear is that users who are privacy conscious but not technically capable may see the 'broken' form and give up there.  I don't have sources off the top of my head, but I've read in UX design articles that every action a user needs to take to accomplish a task reduces their likelihood of accomplishing it..

In this case that being to follow link to potentially shady looking site (depending on subjective interpretation of user) and entering their email to a form that doesn't work, reviewing browser console to determine why it failed, researching messages to find cause, then investigating settings or searching for a way to disable on their own before changing the settings, reloading the site, and entering their email.

**Comment by groovecoder** [comment]
Thanks for the input @targaryen. I'm going to edit your comment to a summary+details format in case this issue gets very noisy.

I'm personally a fan of [Privacy Pass](https://privacypass.github.io/) tech, and we may have an opportunity to collaborate with Troy on implementing it.

**Comment by groovecoder** [comment]
Another consideration ... but I'm afraid it's to spammy & scammy (opens up phishing attack vector) ...

When someone scans an email address, automatically (after some threshold? by some heuristic?) send an email to the scanned email address to inform them that someone has scanned them?

**Comment by groovecoder** [comment]
No, I don't believe we will receive your notifications from HIBP if you opt out. But I'll open a line with Troy to consider if we can make that happen.

**Comment by pdehaan** [comment]
Wait, are we directing people to HIBP, or are we collecting the email address on our side and sending the address/SHA to troy's server?
Not sure if it feels odd that users would sign up to "our" service, but then have to opt out on service B.

But yeah, it may be nice to include both an Unsubscribe and Opt-out link in our email footers.

Also curious if it's possible to un-opt-out if you ever change your mind in the future. Or what happens if you've signed up, explicitly opted out, and then try resubscribing. Does a new sign up override an opt-out?

**Comment by groovecoder** [comment]
@pdehaan undecided on exactly how we would do this. needs prioritization by PM and then UX design.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
