### ISSUE TITLE
Activate delete-unverified-subscribers script

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#471]
When DB backups are verified, start running `scripts/delete-unverified-subscribers` script.

Note: We should add messaging to the verification emails to reflect that verification links are only valid for 24 hours. (Current default)

**Comment by mheubusch** [comment]
Proposed message for email: The verification button is valid for 24 hours. After that, you will need to sign up again. 

Proposed message for any resulting error pages due to expired verification: The verification email is expired. You will need to sign up again, and reply to the verification email within 24 hours.

**Comment by groovecoder** [comment]
Thanks @mheubusch. On the site error pages, we won't know why the verification token is invalid. The 3 possibilities are:

- The token has expired
- The user previous unsubscribed
- The token never existed

Do you think it's okay to show this "expired" error message in all those cases?

**Comment by mheubusch** [comment]
gah - can you remind me of the current error a user gets in cases 2 and 3? i can build on that.

**Comment by groovecoder** [comment]
"This email address is not subscribed to Firefox Monitor."

https://monitor.firefox.com/user/verify?token=123456789

**Comment by mheubusch** [comment]
This email address is not subscribed to Firefox Monitor. You can sign up again and reply to the verification email within 24 hours to complete your subscription.

**Comment by pdehaan** [comment]
But I think bonus points if we can either:

a) Find a way to update the default error page and include a "sign up" form.

b) Redirect the users to a "resubscribe" template which displays the error message above and includes a sign up form (and possibly auto-fills the supplied email address into the form so users only have to click the "sign up" button instead of retyping their email address on a second page).

**Comment by groovecoder** [comment]
@betsymi or @mheubusch before I close this issue, should we add copy to the signup dialog to tell the user they need to click their verification link within 24 hours?

![screen shot 2018-10-02 at 9 29 10 am](https://user-images.githubusercontent.com/71928/46355079-b35b6100-c625-11e8-94df-b0b6047ee4d7.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
