### ISSUE TITLE
Change breach landing page to show "Not Found"/404 for unkown breaches

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#649]
https://monitor.firefox.com/?breach=List

Shows "Cannot read property 'IsSensitive' of undefined" but it should just show a 404.

**Comment by pdehaan** [comment]
Bug should be here (L12) where we access an `[0]` before seeing if we had any results, and the obviously L14 where we're calling `.IsSensitive`.

https://github.com/mozilla/blurts-server/blob/12f6e8e64efb9fdc7f780a9c3063b4315f5f5446/controllers/home.js#L10-L17

Oddly, I think this _used_ to work in the past, and if you tried accessing a breach that didn't exist (or wasn't known to Monitor yet) it'd just display the homepage instead of a featured breach.

**Comment by groovecoder** [comment]
Re-opening for the 2nd half of this fix, which is to return with a `404` status code instead of a `500`

**Comment by groovecoder** [comment]
Closed (again)!
