### ISSUE TITLE
Add utm_content url param to unsubscribe links in emails

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#650]
We include an unsubscribe link in the verification email. But, if a user doesn't verify their subscription within 24 hours, we delete their verification token, so that unsubscribe link sitting in their email inbox will send them to a "This email address is not subscribed to Firefox Monitor." error.

**Comment by pdehaan** [comment]
What about a case where a user signs up, verifies their account, and then wants to unsubscribe (in a month or nine). Would the original unsubscribe link in the onboarding email still work? Or would users need to wait until they got a new breached account email in order to be able to unsubscribe from future emails?

**Comment by groovecoder** [comment]
True. They should also receive a report email after they verify, which could include their unsubscribe link. This needs UI decision.

**Comment by groovecoder** [comment]
@jsavory - what do you think?

**Comment by jsavory** [comment]
We should definitely have the option to unsubscribe from more than just the verification. I think the option to unsubscribe is in the footer though? We should probably include the footer with the option to unsubscribe on every email.

**Comment by sandysage** [comment]
@lesleyjanenorton Let's try to get this landed in with the FxA integration feature work so we have as much visibility as possible going into the transition, if not sooner.
