### ISSUE TITLE
The text is partially translated in some languages (e.g. Japanese, Italian)

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#656]
[Affected versions]:
- FIrefox 63.0.3

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate tohttps://fx-breach-alerts.herokuapp.com/
2. Click on "Get Your Report" and write a valid email.
3. Go to your email inbox and verify your subscription. 
4. In about:preferences change the language to Japanese [ja].
5. Refresh the "Your Firefox Monitor report is on its way" page and observe the page.   

[Expected result]:
- Everything is translated to Japanese. 

[Actual result]:
- The page is partially translated.
- "Your Firefox Monitor report is on its way. Data breaches can affect anyone. Spread the word so your friends and family can check to see if their online accounts are safe." is still in the language that was previously selected. 

[Regression]:
- It's not a regression.

[Additional Info]:
- Please look at the attached image. 
![imgpsh_fullsize 1](https://user-images.githubusercontent.com/42799381/49443993-90d8f600-f7d6-11e8-9064-c3f58cca168a.png)

- This also happens for  Italian [it], too. 
- If the language is set to German, the "Ü" is replaced with "+".
![imgpsh_fullsize 3](https://user-images.githubusercontent.com/42799381/49450772-6bec7f00-f7e6-11e8-87a3-3a517b0cdf66.png)

**Comment by pdehaan** [comment]
Not sure what the expected behavior for Japanese is, but it is 95% translated (per https://pontoon.mozilla.org/ja/firefox-monitor-website/), so I expect a few strings to be missing.

Similarly, Italian is [95% translated](https://pontoon.mozilla.org/it/firefox-monitor-website/).

Not sure about the German issue. I see the "+" in the screenshot in the heading, but that's also the string that I see in the .ftl file:

https://github.com/mozilla/blurts-server/blob/c2a02b74af8fb1c7c000c6eb09115b415e594585/locales/de/app.ftl#L181

Which is the German version of:

https://github.com/mozilla/blurts-server/blob/c2a02b74af8fb1c7c000c6eb09115b415e594585/locales/en/app.ftl#L252

**Comment by groovecoder** [comment]
I think we close this. It's expected that some languages will show partial translations.
