### ISSUE TITLE
FxA "self-hosted email form" metrics tracking

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#711]
FxA would like to measure the "top of funnel" metrics for FxA signups. For "self-hosted email forms" like Monitor has, we need to send [a `fetch` request to their `metrics-flow` url](https://github.com/mozilla/application-services/blob/master/docs/accounts/metrics.md#self-hosted-email-forms-and-metrics-tracking-aka-the-fxa-email-first-flow).

But first, we need to ask FxA if our email scan form constitutes a "self-hosted email form" as part of their top-of-funnel. @sandysage can you handle coordinate that with FxA team?

**Comment by shane-tomlinson** [comment]
cc @irrationagent

**Comment by shane-tomlinson** [comment]
cc @irrationalagent

**Comment by irrationalagent** [comment]
@groovecoder for an example implementation, you can see how the activity stream did this for the about:welcome page here: https://github.com/mozilla/activity-stream/blob/06aeeb331e9dd497e4d115d0e6cba51b9b25b36c/content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx#L27

For your case, I see three entrypoints on the landing page:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/5625313/52295114-3bd17180-2938-11e9-96bc-9d655f19bfca.png">

as well as similar ones on /scan. 

The idea is to `fetch` from the FxA endpoint when the page loads so that our metrics have a sense of how many users are viewing those CTAs. since all three are on the same page you have two options as I see it:

Option 1: have a separate `fetch` attached to each of the three CTAs. they would each have their own value for the`entrypoint` parameter that is attached to the call. e.g. `fx-monitor-signin-link`, `fx-monitor-green-button` etc. You would then append the same value to the URL when you actually direct the user to the FxA form. This would allow you/us from the FxA-side to determine the conversion rate of each of the three points separately. And, so long as you keep the prefix constant (e.g. `fx-monitor`), we will be able to easily collapse over all of them to get a more general funnel.

Option 2: Simpler, you could just make a single `fetch` on page load with the more general entrypoint `fx-monitor` (again, keep the same value in the URL when directing to FxA). This is less fuss but it will only allow you/us to track the overall conversion rate without the detail of where users are clicking. For a more detailed analysis, we could also piece together the interaction data from the monitor GA and the FxA events. But if we end up doing that we will probably wish we just did Option 1. 

From the point of view of FxA, (2) is probably enough for our purposes. But I suspect that @sandysage might want (1).

**Comment by sandysage** [comment]
Alas, @irrationalagent suspects correctly. We need to know the conversion rate of each of the three points separately.

For context, 3 calls to action are a usability concern. We know we need change the approach with the V2 website updates, but we don't yet have a baseline for conversion on each of these 3 calls to action. By tracking each of these entry points we can better measure and quantify the results of our future changes.

**Comment by lesleyjanenorton** [comment]
> Option 1: have a separate `fetch` attached to each of the three CTAs. they would each have their own value for the`entrypoint` parameter that is attached to the call. e.g. `fx-monitor-signin-link`, `fx-monitor-green-button` etc....

@irrationalagent  We went with Option 1. The[`/metrics-flow`](https://mozilla.github.io/application-services/docs/accounts/metrics.html#self-hosted-email-forms-and-metrics-tracking-aka-the-fxa-email-first-flow) documentation mentions a `form-type` parameter. Given that our entrypoints are buttons, do we need still to add this? Also, are there any conventions we should recognize with the `utm_campaign`? Thanks!

**Comment by irrationalagent** [comment]
Use `email` for form type for now, I know it's technically not true in your
case but it's the only value we support at the moment. For utm campaign
anything that passes the regex will work. In the future it could be used to
track referrals to the monitor page if the referrer passes you a parameter.
For now it could just be redundant with utm source. Nothing will fail if
it's null but we tend to prefer non empty parameters even if they're
redundant.
