### ISSUE TITLE
User Says They're Getting Multiple Breach Reports Emails

### ISSUE THREAD

**Issue by betsymi** [mozilla/blurts-server#712]
![multiplebreachreports](https://user-images.githubusercontent.com/43555492/51618236-8a701c00-1ef3-11e9-833c-55fe7f60adef.png)

**Comment by betsymi** [comment]
[Redacted] first comment to remove user's name.

**Comment by groovecoder** [comment]
I can reproduce this by:

* Clicking the "Verify my Email" button multiple times
* Refreshing the http://localhost:6060/user/verify?token=f62eb1af-c89d-46a4-9e1e-4dc36f915715 page

Each time I click or refresh I get another report.

We could update the `/user/verify` code to:
If user verified:
  return
Else:
  Send report
  Mark user verified

That would stop duplicate reports caused by multiple clicks or refreshes.

@sandysage - priority for this one?
