### ISSUE TITLE
The user cannot go back to the homepage by clicking on the Firefox Monitor logo

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#782]
[Affected versions]:
- Firefox 65.0.1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to http://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net
2. Click on the "Sign in" button from the upper right corner of the page.
3. Follow the FxA flow and Sign in with an account.
4. Click on the Firefox Monitor from the https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/scan/latest_breaches page.

[Expected result]:
- The user is redirected to homepage https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/

[Actual result]:
- The page refreshes but the the user is not redirected to the https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/

[Regression]:
- N/A

[Additional Notes]:
- If spamming the Firefox Monitor logo by clicking it for a couple of times the following error is displayed on the page:  `Error Page not found.`
- It seems that the above error also happens if refreshing the webpage for ~10 times.

**Comment by lesleyjanenorton** [comment]
Once a user has signed in, their default Monitor page is the "user dashboard." I'm going to leave this issue open for further commentary because I think it may end up being a major point of confusion/frustration for signed in users.

**Comment by sandysage** [comment]
I think we can reasonably address this concern in the new website version we're creating - creating a distinctive experience between a signed-in and signed-out state. I'll ask that @betsymi and @changecourse correct me if not.

While I recognize that this could be confusing with our current implementation, I have to wonder how many people are actually attempting to go back to the original, not-signed-in homescreen and why. Is it to revisit the content? Is it because they can't find the 'scan another email'?

Since we're planning to handle this use case more holistically, I'm inclined to leave this issue in our Inbox for triage if/when we discover more about what someone expects to get from hitting the home icon.

**Comment by betsymi** [comment]
@sandysage +1 to your comment. I'm good with this.
