### ISSUE TITLE
Deleting a secondary email issues an application error

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#890]

**Comment by groovecoder** [comment]
I was unable to reproduce this error on either https://monitor-v2.herokuapp.com/user/preferences or on my http://localhost:6060/user/preferences. (It may have been fixed by https://github.com/mozilla/blurts-server/pull/897? ) I'm going to close this to focus on things I can reproduce.

If you (or QA) can find the reliable steps-to-reproduce this, please re-open.

**Comment by pdehaan** [comment]
I'm not logged in to FxA on monitor-v2, but I seem to be getting an application error when visiting https://monitor-v2.herokuapp.com/user/preferences (but not the homepage of the server, which makes me think the server is alive).

**Comment by groovecoder** [comment]
@pdehaan can you file that as a separate issue? Basically, "Visiting /user/preferences without a session triggers an application error" ?
