### ISSUE TITLE
Apollo is categorized as website breach. Should be data aggregator. 

### ISSUE THREAD

**Issue by betsymi** [mozilla/blurts-server#950]
Apollo appears as a website breach on https://fx-breach-alerts.herokuapp.com/breach-details/Apollo.

**Comment by pdehaan** [comment]
Currently, the only breach classified as "Data Aggregator" is the **Exactis** breach (via https://fx-breach-alerts.herokuapp.com/breaches and toggling only the Data Aggregator button).

I did see we're special casing "Exactis" in the [`getBreachCategory()`](https://github.com/mozilla/blurts-server/blob/dc003732eb6521b77bc3b491db0296fa22ff4473/template-helpers/breach-detail.js#L16-L33) method, but maybe stuff without Domains is getting picked up by earlier rules, so all of these **empty-Domain breaches** are categorized as "Unverified Breach"es:

- https://fx-breach-alerts.herokuapp.com/breach-details/2844Breaches
- https://fx-breach-alerts.herokuapp.com/breach-details/AntiPublic
- https://fx-breach-alerts.herokuapp.com/breach-details/Collection1
- https://fx-breach-alerts.herokuapp.com/breach-details/CouponMomAndArmorGames
- https://fx-breach-alerts.herokuapp.com/breach-details/DataEnrichment
- https://fx-breach-alerts.herokuapp.com/breach-details/ExploitIn
- https://fx-breach-alerts.herokuapp.com/breach-details/VINs
- https://fx-breach-alerts.herokuapp.com/breach-details/KayoMoe

### Spam List Breaches:
- https://fx-breach-alerts.herokuapp.com/breach-details/B2BUSABusinesses
- https://fx-breach-alerts.herokuapp.com/breach-details/OnlinerSpambot
- https://fx-breach-alerts.herokuapp.com/breach-details/SaverSpy
- https://fx-breach-alerts.herokuapp.com/breach-details/TrikSpamBotnet

### Data Aggregator Breaches:
... but oddly, didn't appear on the /breaches page
- https://fx-breach-alerts.herokuapp.com/breach-details/ElasticsearchSalesLeads 
- https://fx-breach-alerts.herokuapp.com/breach-details/Estonia
- https://fx-breach-alerts.herokuapp.com/breach-details/MasterDeeds
- https://fx-breach-alerts.herokuapp.com/breach-details/YouveBeenScraped

That's the hardest thing about trying to categorize breaches. A breach can technically be in 2-5 categories at the same time, so choosing just one can sometimes get confusing or misleading. For example, https://fx-breach-alerts.herokuapp.com/breach-details/Zoosk ([HIBP JSON](https://haveibeenpwned.com/api/v2/breach/Zoosk)) is both `IsVerified=false`, and `IsSensitive=true` (none of the other `getBreachCategory()` checks seem to apply). But should we label it as **Sensitive** or **Unverified**?
The workaround would maybe be to display a list of categories on the /breach-details/ page instead of just a singular category. We have space, and should have zero l10n impact (maybe).

**Comment by betsymi** [comment]
I see, so if a breach is classified as something else, that takes precedence. Verified and unverified are HIBP classifications, but not particularly useful to users. Can we prioritize classifying breaches that are known data aggregators as data aggregators?

This distinction has been a big point of confusion for existing users and from what we learned in user testing. So we designed a website breach detail page and a data aggregator detail page that serve different information to users about those types of breaches so they can better understand what they can do to mitigate the damage.

**Comment by pdehaan** [comment]
What classifies something as a data aggregator breach? Just breaches that don't have a Domain? Could something be a data aggregator breach _and_ a spam list breach?

**Comment by groovecoder** [comment]
To address the most important problem of data aggregators confusing users, we could update the hard-coded special-case array at the top of `getBreachCategory` to include the other data aggregators. I.e.,

```js
function getBreachCategory(breach) {
  if (["Exactis", "YouveBeenScraped", "ElasticsearchSalesLeads", "Estonia", "MasterDeeds"].includes(breach.Name)) {
    return "data-aggregator-breach";
  }
  ...
```
